-- Part 8 - How to get the last generated identity column value in SQL Server

Use myDatabase
GO

CREATE TABLE Test1
(
ID INT IDENTITY(1, 1),
value NVARCHAR(20)
);

CREATE TABLE Test2
(
ID INT IDENTITY(1, 1),
value NVARCHAR(20)
);

INSERT INTO Test1 VALUES ('X');

SELECT * FROM Test1;

SELECT SCOPE_IDENTITY();

INSERT INTO Test1 VALUES ('X');

SELECT SCOPE_IDENTITY();

SELECT @@IDENTITY;

CREATE TRIGGER trForInsert ON Test1 FOR INSERT
AS
BEGIN
	INSERT INTO Test2 VALUES('YYYY')
END

SELECT * FROM Test1;
SELECT * FROM Test2;

INSERT INTO Test1 VALUES ('X');

SELECT SCOPE_IDENTITY();

SELECT @@IDENTITY;

SELECT * FROM Test1;
SELECT * FROM Test2;

INSERT INTO Test2 VALUES ('zzz');

SELECT SCOPE_IDENTITY();

SELECT @@IDENTITY;

SELECT IDENT_CURRENT('Test2');